name: 🛠️ Build
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  linux:
    runs-on: "ubuntu-latest"
    name: 🐧 Linux
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Setup Godot
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
          unzip Godot*.zip
          rm Godot*.zip
          mv Godot* godot
          chmod +x ./godot
      - name: Build
        run: |
          mkdir -p build/linux
          ./godot -v --export-release "Linux" --headless ./build/linux/$exportName.x86_64
          tree #for testing