name: 🛠️ Build
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  linux:
    # Based on https://github.com/godotengine/godot-build-scripts/blob/3.x/build-linux/build.sh
    runs-on: "ubuntu-latest"
    name: 🐧 Linux
    env:
      SCONSFLAGS: mono_static=yes
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Setup Godot
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
          unzip Godot*.zip
          rm Godot*.zip
          mv Godot* godot
          tree ./ #for testing