name: Godot CI

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on PRs to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Godot
        uses: firebelley/godot-export@v1.4
        with:
          godot-version: '4.3'

      - name: Build for Windows
        run: godot --export "Windows Desktop" builds/Windows/Game.exe

      - name: Build for macOS
        run: godot --export "Mac OSX" builds/Mac/Game.dmg

      - name: Build for Linux
        run: godot --export "Linux/X11" builds/Linux/Game.x86_64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Game-Builds
          path: builds/
